### ISSUE TITLE
可唔可以出手機版？

### ISSUE THREAD

**Issue by laubonghaudoi** [aaronhktan/jyut-dict#13]
呢隻字典真係好好用，如果上iOS同Android就好了。

**Comment by aaronhktan** [comment]
你好！我唔識整手機軟件，但係手機上邊已經有一個好好嘅中文/廣東話/英文字典，叫做Pleco Dictionary。如果你沒用過，我真係好推薦呢個app！

Android: https://play.google.com/store/apps/details?id=com.pleco.chinesesystem

iOS: https://itunes.apple.com/us/app/pleco-chinese-dictionary/id341922306

**Comment by laubonghaudoi** [comment]
哦，真係唔該嗮，我都唔知有呢隻字典。不過我睇咗下佢都係默認查普通話發音嘅？如果要查粵語發音仲要自己另外下載詞庫，一般都無人會注意到。我搵咗下好似剩得呢個字典係可以默認粵語嘅，不過有廣告有啲遺憾[粵韻漢典發聲中文字典](https://apps.apple.com/us/app/%E7%B2%B5%E9%9F%BB%E6%BC%A2%E5%85%B8%E7%99%BC%E8%81%B2%E4%B8%AD%E6%96%87%E5%AD%97%E5%85%B8/id1253572344)

**Comment by dosentmatter** [comment]
Would also be useful to release the addon dictionaries and pleco user dictionaries.
