### ISSUE TITLE
Problème d'ajout de dictionnaires

### ISSUE THREAD

**Issue by vintotal** [aaronhktan/jyut-dict#130]
Depuis la dernière mise à jour (v2.23.0408), je n'arrive plus à ajouter des dictionnaires sous Windows. Tel que j'avais décrit dans un rapport passé ( #67 ), je dois supprimer tous les dictionnaires, puis ajouter ceux en français. Malheureusement, maintenant, le dictionnaire choisi ne s'ajoute pas. Je ne peux pas ajouter le CFDICT 2016 ou les phrases Tatoeba mandarin-français.

Pour voir le bogue.
1. Supprimer tous les dictionnaires
2. Télécharger un dictionnaire sur Github, exemple:  Jyut-Dictionary_Addon-CFDICT-2016.db 
3. Aller dans les réglages et essayer d'ajouter un dictionnaire

https://user-images.githubusercontent.com/1743914/234473053-82cc92f8-83ee-4a8c-9c25-52c217a4a426.mp4

**Comment by aaronhktan** [comment]
Hum. Je n'arrive pas à reproduire ce bogue sur mon propre ordinateur. L'effacement et l'ajout des dictionnaires fonctionne comme prévu.

L'application ne devrait pas vous permettre de supprimer tous les dictionnaires - le bouton pour supprimer le dernier dictionnaire devrait être désactivé quand il reste seulement un dictionnaire. Je me demande si, en supprimant le dernier dictionnaire, ça a causé des problèmes pour l'application.

Dans tous les cas, vous pouvez effacer la base de données qui contient les dictionnaires, puis le remplacer avec l'un des fichiers que vous avez téléchargés. Cela aidera l'application à « redémarrer » la base de données.

1. Fermez l'application.
2. Naviguez au dossier `C:\Users\VOTRE_NOM_D'UTILISATEUR_ICI\AppData\Local\Aaron Tan\CantoneseDictionary\Dictionaries`.
3. Supprimez le fichier `dict.db`.
4. Renommez l'un des fichiers que vous avez téléchargés, ex. `Jyut-Dictionary_Addon-CFDICT-2016.db`, en `dict.db`.
5. Déplacez le fichier que vous avez renommé vers le dossier.
6. Redémarrez l'application et ajoutez les autres dictionnaires comme auparavant.

J'espère que ces instructions vous aideront à résoudre le problème! N'hésitez pas à laisser un commentaire si vous avez besoin plus d'aide, ou fermer le ticket si vous parvenez à résoudre le problème!

(En passant, est-ce que vous préférez que je vous tutoie ou que je vous vouvoie?)

**Comment by vintotal** [comment]
Bonjour! Merci de votre réponse.

J'ai essayé d'appliquer votre méthode mais j'ai échoué. Voici ce que j'ai d'abord essayé:

1. Fermer Jyut
2. Supprimer dict.db du dossier AppData\Local\Aaron Tan\CantoneseDictionary\Dictionaries
3. Copier Jyut-Dictionary_Addon-CFDICT-2016.db dans AppData\Local\Aaron Tan\CantoneseDictionary\Dictionaries
4. Renommer Jyut-Dictionary_Addon-CFDICT-2016.db en dict.db

Le résultat a été que le programme n'a aucun dictionnaire actif (la liste est vide). Je ne peux pas ajouter de dictionnaire non plus.

J'ai essayé la version avec installateur EXE, la version portable aussi. Heureusement j'ai fait une copie de sauvegarde de mes dictionnaires précédents, alors si je recopie l'ancien dict.db (d'avant la mise à jour) sur AppData\Local\Aaron Tan\CantoneseDictionary\Dictionaries, alors je peux continuer d'utiliser CFDICT et Tatoeba comme avant. Je ne sais pas pourquoi il y a un dict.db dans le dossier principal (C:\Program Files\Jyut Dictionary) aussi.

Juste pour être certain, j'ai essayé de:

1. tout désinstaller
2. supprimer C:\Program Files\Jyut Dictionary
3. supprimer  AppData\Local\Aaron Tan\CantoneseDictionary\Dictionaries

Ensuite j'ai:

1. Réinstallé le programme avec les options par défaut
2. Essayé d'ajouter un dictionnaire Jyut-Dictionary_Addon-CFDICT-2016.db (sans enlever les autres dictionnaires avant)
3. Constaté que le dictionnaire ne s'ajoute pas

https://user-images.githubusercontent.com/1743914/235159897-cc85e25d-4b74-44fd-aed9-27a10b012c0d.mp4

J'ai remarqué qu'il y a des fichiers dict.db qui apparaissent avec un numéro après. Est-ce normal?

![Presse-papier02](https://user-images.githubusercontent.com/1743914/235160142-80f0e9e8-ebba-4baa-93ea-80e149e973cf.jpg)

**Comment by aaronhktan** [comment]
Est-ce que vous avez essayé d'ajouter un autre dictionnaire (comme MoeDict)? C'est possible que le fichier CFDICT-2016 est corrompu, peut-être c'est ça le problème.

Pour les numéros après, oui c'est normal - ce sont des sauvegardes automatiques! Quand un usager ajoute/supprime/remplace un dictionnaire, Jyut fait une sauvegarde automatique avant l'ajout/l'enlèvement du dictionnaire, au cas où l'application rencontre un problème irrécupérable.

**Comment by vintotal** [comment]
Bonjour. Voici ce que j'ai fait:
Supprimer « mon » ancien dict.db (contenant CFDICT pré-2016 et Tatoeba mandarin anglais)
Copié le dict.db du dossier \Program Files\Jyut Dictionary vers AppData\Local\Aaron Tan\CantoneseDictionary\Dictionaries
Téléchargé Jyut-Dictionary_Addon-Tatoeba-cantonais-francais
Ajouté Jyut-Dictionary_Addon-Tatoeba-cantonais-francais

Je n'ai rien supprimé et le dictionnaire a été ajouté comme prévu. Dommage que ça ne fonctionne pas pour le CFDICT 2016 ou le Tatoeba mandarin français.

![imagen](https://user-images.githubusercontent.com/1743914/235331266-1bc81f1b-3f59-42d0-99f1-68748b03483c.png)

J'ai essayé par curiosité d'ajouter les dictionnaires 2.23 à la version 0.20, mais la version n'était pas la même et j'ai échoué.

J'ai essayé de télécharger la version 0,20 et d'y ajouter le CFDICT 0.20: ça fonctionne.

![imagen](https://user-images.githubusercontent.com/1743914/235331762-4b57044d-04bc-4067-8a62-7bdc56efd575.png)

J'ai essayé d'a ajouter le CFDICT 1.22 à la version 2.23 : ça fonctionne.

![imagen](https://user-images.githubusercontent.com/1743914/235331881-932774ba-fbd3-4a7f-aeb9-855a3849d258.png)

**Comment by aaronhktan** [comment]
Wow, c'est vraiment un problème bizarre; j'ai essayé avec mon autre ordi qui tourne sur Windows 10 et l'ajout des dictionnaires fonctionne là-aussi.

Une dernière chose à essayer : j'ai crée un fichier (que vous pouvez accéder en cliquant [ce lien](https://www.icloud.com/iclouddrive/075pAHUEFnkug4CDbK7s9EKCQ#dict)) qui contient les dictionnaires CFDICT, CFDICT-2016, et Tatoeba mandarin-français. Pouvez-vous essayer le (en le téléchargeant et le déplaçant vers `C:\Users\VOTRE_NOM_D'UTILISATEUR_ICI\AppData\Local\Aaron Tan\CantoneseDictionary\Dictionaries`)?

**Comment by vintotal** [comment]
Formidable! J'ai remplacé mon vieux dict.db par le vôtre et je peux désormais voir les trois dictionnaires. Toutes les définitions sont affichées! Bref, je ne sais pas d'où venait le problème, mais vous l'avez admirablement contourné. 😊

J'ai même ajouté le tatoeba cantonais-français avec succès. J'ai remarqué, même si le mandarin a été installé avant, que les phrases-exemples en cantonais s'affichent **avant** les phrases-exemples en mandarin. Voir l'image plus bas. ⬇️

![imagen](https://user-images.githubusercontent.com/1743914/235400150-a789f3f7-1178-41b2-b9b5-cdc5add9158f.png)

**Comment by aaronhktan** [comment]
Ouais, c'est parce que toutes les phrases de Tatoeba ont un identificateur unique assigné par Tatoeba. Quand on fait une recherche pour les phrases qui contiennent une entrée, le « groupe » de phrases qui s'affiche en premier dépend entièrement de l'identificateur du premier phrase de ce groupe. C'est probablement quelque chose que je pourrais regarder de plus près quand j'aurai un peu plus de temps libre...

Bon, puisque le problème initial a été résolu, je vais fermer ce ticket! Merci de votre feedback :)
