### ISSUE TITLE
error with mandarin TTS

### ISSUE THREAD

**Issue by ohnekopf** [aaronhktan/jyut-dict#132]
**Describe the bug**
Mandarin TTS just says "chinese render" instead of the word im looking up

**To Reproduce**
open any entry and click on the speaker icon besides the `PY` pinyin thing

**Desktop (please complete the following information):**
Debian Bullseye
**Additional context**

[recording](https://voca.ro/1fozUn3TXdV0)

**Comment by aaronhktan** [comment]
Huh, that's weird (but also kind of funny). Unfortunately since I can't repro on my Pop_OS devices, I don't think I'll be able to fix this problem. :(

In the future, I'll try to build in some network text-to-speech since this has caused so many issues on Linux.

**Comment by ohnekopf** [comment]
hearing "CHINESE LETTER CHINESE LETTER" repeated over and over had me in tears, i must admit
Anyway, i tried the qt5 hello_speak tts testing little program and for some reason the mandarin voices are there, they are just for some weird reason under  the "language" "C" along with a lot of weird stuff like ancient greek, armenian and hatian creole, instead of showing up as a standalone  Chinese category. pretty bizarre stuff.
