### ISSUE TITLE
Plantage lors d'une combinaison de touches

### ISSUE THREAD

**Issue by vintotal** [aaronhktan/jyut-dict#133]
**Describe the bug**
Après l'ouverture du programme et avec le dictionnaire de chinois traditionnel _ou_ simplifié sélectionné, le logiciel plante si la première lettre écrite est A majuscule (touches MAJ + A).

**To Reproduce**
1. Ouvrir le programme.
2. Appuyer sur **MAJ + A** en même temps.
3. Constater l'erreur.

**Screenshots**
![imagen](https://github.com/aaronhktan/jyut-dict/assets/1743914/db331023-c9e7-4d78-9d36-17b886e928aa)

**Desktop (please complete the following information):**
 - OS: Windows 6.3
 - Version: 2.23.0408

J'ai essayé **MAJ + C**, le logiciel ne plante pas.

(En passant, le mot « Magnifier » (qui sert à grossir les caractères) pourrait être remplacé par « Agrandir ». En français « Magnifier » signifie « vanter, montrer la gloire, exalter ». )

**Comment by aaronhktan** [comment]
D'habitude quand l'appli plante, c'est à cause d'une erreur qui s'est produite en essayant de convertir du Jyutping en API ou du Pinyin en Zhuyin ou API. Est-ce que vous avez déjà mis à jour tous les dictionnaires que vous utilisez?

Si oui, et l'appli plante toujours, pouvez-vous exporter et m'envoyer la base de données? J'aimerais bien savoir quelle entrée contient l'erreur....

Re: magnifier - oups! Je vais le re-traduire our la prochaine version, merci de me l'avoir signalé!

**Comment by vintotal** [comment]
Voici ce que j'ai essayé avec la version 2.23.0408.

1. Supprimer tous les dictionnaires sauf le Tatoeba cantonais-français
2. Ajouter ces trois dictionnaires, dans l'ordre: Tatoeba mandarin-français, CFDICT 21016, CFDICT
3. Confirmer que le réglage de la translittération du mandarin est à Bopomofo, et cantonais laissé sans sélection.

Le résultat est le même qu'avant mes opérations, c'est-à-dire que choisir la recherches selon un des deux dictionnaire chinois (tradionnel ou simplifié) et appuyer sur MAJ+A fait planter le logiciel. J'ai ensuite essayé de supprimer tous les dictionnaires sauf le CFDICT; le problème persiste.

Voici le fichier dict.db extrait de mon dossier AppData\Local\Aaron Tan\CantoneseDictionary\Dictionaries puis comprimé.
[dict.zip](https://github.com/aaronhktan/jyut-dict/files/12495508/dict.zip)

**Comment by aaronhktan** [comment]
Il paraît que l'entrée qui a causé le problème est « 城際高鐵 », dont le Pinyin est mal formé (« chzng2  » au lieu de « cheng2  »).  J'ai téléversé une nouvelle version du dictionnaire qui corrige le Pinyin - vous pouvez le télécharger du site web. J'aurai une solution plus permanente pour la prochaine version du logiciel.

**Comment by vintotal** [comment]
Merci beaucoup de vos efforts. J'ai téléchargé le CFDICT que vous avez téléversé et hélas le logiciel plante encore.

Si j'utilise:
Tatoeba + CFDICT2016 + CFDICT nouveau: MAJ+A fait planter
Tatoeba + CFDICT nouveau: MAJ+A fait planter
Tatoeba + CFDICT2016: MAJ+A fait planter
Tatoeba seulemen: MAJ+A ne fait pas planter.

Je pense que je vais me contenter de cette version et simplement ne pas utiliser MAJ+A. Ce n'est pas un gros problème et de toute façon ce bogue sera réglé dans la prochaine version (que je n'utiliserai pas car elle sera basée sur Qt6 😅).
