### ISSUE TITLE
Using the jyutping dictionary in Python

### ISSUE THREAD

**Issue by tshmak** [aaronhktan/jyut-dict#32]
Hi, 

Is it possible to use your package as a jyutping dictionary in python? 

Thanks, 

Tim

**Comment by aaronhktan** [comment]
Hi Tim - if you are looking for a library to convert Chinese characters to Jyutping, somebody has done that over [here](https://github.com/lucwastiaux/python-pinyin-jyutping-sentence).

It uses the same source and dictionary as this project (CC-Canto), so it should give the same results.

**Comment by tshmak** [comment]
Thanks a lot!

**Comment by aaronhktan** [comment]
No problem! Good luck with your project!
