### ISSUE TITLE
Support for additional romanization schemes: Bopomofo/Zhuyin, Yale, IPA

### ISSUE THREAD

**Issue by vintotal** [aaronhktan/jyut-dict#33]
大家好！
I downloaded today the programme, I was very happy to see it can use traditional script and there is also a French interface. Bopomofo support is absent and I am unable to import [CFDICT](https://chine.in/mandarin/dictionnaire/CFDICT/) in the dictionary list. Is there a way to enable these two functions?
多謝！

**Comment by aaronhktan** [comment]
Salut vintotal!

Oui, il est possible d'ajouter CFDICT à l'application - la base de données CFDICT est disponible ici:
https://github.com/aaronhktan/jyut-dict/releases/download/v0.20.0525-release/Jyut-Dictionary_Addon-CFDICT.db

Vous pouvez également télécharger les exemples d'utilisation provenant de Tatoeba et leurs traductions vers le français:
https://github.com/aaronhktan/jyut-dict/releases/download/v0.20.0525-release/Jyut-Dictionary_Addon-Tatoeba-Mandarin-Francais.db
https://github.com/aaronhktan/jyut-dict/releases/download/v0.20.0525-release/Jyut-Dictionary_Addon-Tatoeba-Cantonais-Francais.db

En ce qui concerne le Bopomofo, malheureusement, je ne connais pas très bien le système, donc je n'ai aucune façon de vérifier si une implémentation est correcte. C'est pour cela que je n'ai pas explicitement programmé les bases de données de manière qu'elles puissent supporter le Bopomofo. En outre, CFDICT/CEDICT/CC-CANTO ne fournissent que la prononciation en Pinyin dans leurs versions téléchargables... 😢 

---
Hey vintotal!

Yes, you can add CFDICT to the application. The database can be found at the following link:
https://github.com/aaronhktan/jyut-dict/releases/download/v0.20.0525-release/Jyut-Dictionary_Addon-CFDICT.db

You can also download the sentence examples from Tatoeba and their translations into French:
https://github.com/aaronhktan/jyut-dict/releases/download/v0.20.0525-release/Jyut-Dictionary_Addon-Tatoeba-Mandarin-Francais.db
https://github.com/aaronhktan/jyut-dict/releases/download/v0.20.0525-release/Jyut-Dictionary_Addon-Tatoeba-Cantonais-Francais.db

Regarding Bopomofo, unfortunately, I have little experience with the system, so I have no way to verifying that an implementation of it (in this program) would be correct. It's why I haven't explicitly programmed the databases to support Bopomofo. Moreover, CFDICT/CEDICT/CC-CANTO only provide their pronunciation data in Pinyin in the downloadable versions... 😢

**Comment by vintotal** [comment]
Merci de votre réponse aussi rapide! Pour le CFDICT, c'est une excellente nouvelle, je vais l'ajouter tout de suite. :-D

Concernant le bopomofo, je pense qu'il est possible d'obtenir une correspondance exacte entre le pinyin et le bopomofo selon une table de conversion. La page suivante comporte une table qui me paraît exhaustive. J'ai fait une vérification à l'aveuglette de la prononciation de quelques caractères et le bopomofo (appelé « ZhuYin » dans la table) m'a paru exact.
https://terpconnect.umd.edu/~nsw/chinese/pinyin.htm

Comme le CFDICT indique toutes les prononciations en pinyin, j'imagine qu'un algorithme relativement simple pourrait permettre de « lire » le pinyin, mais d'afficher le bopomofo de la colonne adjacente? Je n'ai pas de connaissances en programmation.

**Comment by aaronhktan** [comment]
Ah bon, ça a l'air pas trop compliqué au final. Je vais l'ajouter à la liste de choses à faire.

- [ ] Generate Zhuyin/Bopomofo readings when in the entry header
- [ ] Add setting to enable/disable display of Zhuyin/Bopomofo in UI and backend
- [ ] Add warning that Zhuyin/Bopomofo readings are generated from Pinyin and may not be completely accurate

**Comment by aaronhktan** [comment]
A few thoughts, scoping out work for this issue: https://github.com/aaronhktan/jyut-dict/issues/44#issuecomment-1030753376
