### ISSUE TITLE
Libellé incorrect pour la couleur des tons

### ISSUE THREAD

**Issue by vintotal** [aaronhktan/jyut-dict#34]
Bonsoir,

Dans l'écran des réglages, nous pouvons déterminer les couleurs des caractères selon les tons du cantonais ou du mandarin. Il y a deux rangées de tons, une pour le cantonais (je suppose qu'à 6 tons, c'est le jyutping) et une autre juste en-dessous à 4 tons. Or, les deux sont identifiées « Couleurs de tons en jyutping: ». Est-il possible que le libellé de la deuxième rangée devrait être « Couleurs de tons en pinyin: »?
![imagen](https://user-images.githubusercontent.com/1743914/101231926-79120200-367c-11eb-9547-e5d14d0241a2.png)

**Comment by aaronhktan** [comment]
Oups! Vous avez raison, ça devrait être « Couleurs de tons en pinyin ». 😓
