### ISSUE TITLE
Additional romanization schemes

### ISSUE THREAD

**Issue by LawranceFung** [aaronhktan/jyut-dict#44]
Would you consider adding additional romanization schemes, or considering a pull request for the feature?

**Comment by aaronhktan** [comment]
Yes! It's something I've been looking at (see issue #33 - the discussion is in French but it should be easy to machine translate for understanding).

Some thoughts about it, which I'll write down here as a note:
1. The preferences file currently has four options (prefer Jyutping, prefer Pinyin, only Jyutping, only Pinyin) — the enum is defined [here](https://github.com/aaronhktan/jyut-dict/blob/5cd7e20140544389280b1426cea66f52f378330b/src/jyut-dict/logic/entry/entryphoneticoptions.h#L1). Adding more romanization schemes would entail completely rethinking the preference options. My thoughts: split the option up into five different groups of options:
    * [Show Cantonese romanization - boolean yes/no]
    * [Show Mandarin romanization - boolean yes/no]
    * [Prioritize Cantonese romanization over Mandarin - boolean yes/no]
    * [Select Cantonese romanizations to show - list of options]
    * [Select Mandarin romanizations to show - list of options]
2. Changing the preference means that we'd also need to migrate old preferences to preferences. (e.g. old "Prefer Jyutping" -> new "Show Mandarin yes/Show Cantonese yes/Prioritize Cantonese yes/Mandarin romanizations [Pinyin]/Cantonese romanizations [Jyutping]")
3. There are a bunch of places where these preferences are referenced, and would have to take into account the new enum(s):
    * [ResultListDelegate](https://github.com/aaronhktan/jyut-dict/blob/5cd7e20140544389280b1426cea66f52f378330b/src/jyut-dict/components/entrysearchresult/resultlistdelegate.cpp#L67), where the search results are displayed 
    * [EntryHeaderWidget](https://github.com/aaronhktan/jyut-dict/blob/5cd7e20140544389280b1426cea66f52f378330b/src/jyut-dict/components/entryview/entryheaderwidget.cpp#L127), where the Jyutping/Pinyin are currently displayed in the detail view
    * [SentenceContentWidget](https://github.com/aaronhktan/jyut-dict/blob/5cd7e20140544389280b1426cea66f52f378330b/src/jyut-dict/components/sentencecard/sentencecontentwidget.cpp#L132), where Jyutping/Pinyin are displayed for example sentences
    * [Entry](https://github.com/aaronhktan/jyut-dict/blob/5cd7e20140544389280b1426cea66f52f378330b/src/jyut-dict/logic/entry/entry.cpp#L237), the class that implements the data structure for all entries in the dictionary.
4. For specific romanization schemes, it would be nice to have:
    * **Cantonese**: Yale (second-most-used), Cantonese Pinyin (promoted by HK government), IPA (for linguists). Conversions from Jyutping to these romanization schemes is implemented in a [Wiktionary module](https://en.m.wiktionary.org/wiki/Module:yue-pron) as well as in [PyCantonese](https://github.com/jacksonllee/pycantonese/blob/146e7c5304eaeea8a3829321d2909445c9161166/pycantonese/jyutping/yale.py#L1); an implementation for Jyut Dictionary could probably be inspired by approaches taken by those scripts.
    * **Mandarin**: Zhuyin (used in Taiwan), IPA (for linguists). I will admit that I am less familiar with what's in common use for Mandarin romanization (does anybody still use Tongyong Pinyin?), but I believe Pinyin+Zhuyin+IPA should cover most bases. See [Wiktionary module](https://en.m.wiktionary.org/wiki/Module:cmn-pron) and [Dragonmapper](https://github.com/tsroten/dragonmapper/blob/68eaf43c32725f4b4923c01284cfc0112079e8ab/dragonmapper/transcriptions.py#L223) for some prior art.
5. As discussed in #33, it would be nice to have a warning next to the non-Jyutping/non-Pinyin entries to warn that they are auto-generated and not necessarily accurate.

It would be a non-trivial amount of work. (Which is probably why I've been putting it off for a while, in addition to there being a global pandemic and all.) If somebody is willing to make a PR, I'd be glad to take a look!

**Comment by LawranceFung** [comment]
I don't speak French.  Sorry, I'm not Canadian!  I'll Google or Bing translate it for context.  
I think all the Romanization schemes you mentioned have value and possibly a place in the app.  I'll admit I'm interested in including one I devised myself - http://www.cantonese.sheik.co.uk/phorum/read.php?1,150054 - meant to preserve historical distinctions and compact digraphs for the sake of quick typing and accurate character selection.

**Comment by aaronhktan** [comment]
Hmm, I thought I left a comment here but it doesn't show up. Anyway, that looks cool! I would prioritize Yale / IPA since they are more widespread for the moment – but if I can get the system going, I'll definitely look into your romanization system.

Also, for housekeeping reasons, I'm going to close this as a dupe of #33, just to keep the issues page cleaner. Let me try the keyword:

Duplicate of #33
