### ISSUE TITLE
Add data from ABC Cantonese-English dictionary

### ISSUE THREAD

**Issue by aaronhktan** [aaronhktan/jyut-dict#53]
**Describe the source**
"The ABC Cantonese-English Comprehensive Dictionary ... comprises about 15,000 lexical entries that are unique to the colloquial Cantonese language as it is spoken and written in Hong Kong today."

**Reasoning**
It's a really good additional source of Cantonese expressions and phrases, and it often has etymological explanations absent from other sources. Robert Bauer is a respected Cantonese linguist who has done a lot of work in this field.

**Licensing or cost**
This dictionary costs $99, and can be licensed by developers from Wenlin for personal use. [See here for details](https://wenlin.com/developers).

**Comment by shawkynasr** [comment]
现代粤语词典
[Cantonese-Mandarin dictionary 2021](https://item.jd.com/13466770.html)
They have app as wechat 公众号

**Comment by shawkynasr** [comment]
[粤语发音](https://shyyp.net/)

**Comment by dosentmatter** [comment]
Hi @aaronhktan is ABC Dictionary still included in Jyutdict? I see the parsing code for it https://github.com/aaronhktan/jyut-dict/tree/main/src/dictionaries/abc_ and see it's still mentioned in the README https://github.com/aaronhktan/jyut-dict?tab=readme-ov-file#dictionaries

But I don't see it listed in the dictionaries on the website https://jyutdictionary.com/ and don't see it in the app.

**Comment by aaronhktan** [comment]
@dosentmatter: Yes, unfortunately. I don't have a licence to distribute the dictionary in its completed form; however, you can buy the text file containing all the data from the Wenlin developer website (https://wenlin.com/developers) and generate the database using the parsing script.
