### ISSUE TITLE
Adjust font size

### ISSUE THREAD

**Issue by AlienKevin** [aaronhktan/jyut-dict#64]
Font size of the whole interface is a bit small for me, especially the entries. Would like to adjust font size of toolbar and entries in the Preference. Thanks.

**Comment by aaronhktan** [comment]
Ooh, this is a good point.

I think increasing the size of the toolbar / search bar definitely makes sense (Chinese gets really squished in there). The entry header could also be bigger.

I don't know how much work it would be, so I'll leave this issue open for now. Thank you for bringing it up!
