### ISSUE TITLE
Affichage des définitions dans la liste

### ISSUE THREAD

**Issue by vintotal** [aaronhktan/jyut-dict#67]
**Describe the bug**
Quand le dictionnaire Kaifangcidian et le dictionnaire CFDICT sont installés simultanément, les définitions n'apparaissent pas dans la liste des résultats à gauche, mais sont bel et bien affichées dans la partie de droite (détails).
![avec CC-CANTO](https://user-images.githubusercontent.com/1743914/178920331-f92e1419-b8d0-4d31-a053-00ecf7d664f9.jpg)

**To Reproduce**
1. Installer le logiciel normalement.
2. Avoir Kaifangcidian 開放詞典 et CFDICT installés
3. Rechercher un mot à partir du français.

**Expected behavior**
Les définitions françaises existantes devraient être affichées dans la liste des résultats même si la définition est absente dans le Kaifangcidian.
![sans kai](https://user-images.githubusercontent.com/1743914/178920356-bde58c18-094f-4327-a20b-457921cae59a.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Version 1.22.0207

**Additional context**
Peut-être que permettre la priorisation des dictionnaires (changer l'ordre) pourrait régler ce problème?
![kai](https://user-images.githubusercontent.com/1743914/178920281-9d6add5e-4d8b-4262-808e-77e9b0bd0893.jpg)

**Comment by aaronhktan** [comment]
Hum. Les définitions sont affichées selon l’ordre d’installation des dictionnaires qui les contiennent - par exemple, si vous avez installé CFDICT avant d’installer Kaifangcidian, les définitions en français apparaîtront avant les définitions en mandarin.

Une solution, vu que la priorisation n’est pas possible en ce moment, serait de désinstaller Kaifangcidian puis le réinstaller pour que ses définitions apparaissent en bas de la page.
